### ISSUE TITLE
Discussion about mailto:-links

### ISSUE THREAD

**Issue by Wekra** [fsi-hska/iwi-website#12]
I'm not sure if we want to have mailto:-links or plaintext mailadresses on the website since these make it easy for spam-crawlers to add our new domain to their lists.

I would suggest to have them "masked" somehow or only provide them in some kind of form like `recipient [at] domain [dot] tld` so that they have to overcome at least a small hurdle :thinking:

Update 2020-09-15:
After discussing in our tweekly, we decided it would be the best to go for a dynamic spam prevention using javascript or php including encryption of some sort.
An example of this would be the implementation on the [University website](https://www.hs-karlsruhe.de/), for example this element:
```html
<a href="javascript:linkTo_UnCryptMailto(%27ocknvq%2CockndqzBju%5C%2Fmctnutwjg0fg%27);">
mailbox<span style="display:none">spam prevention</span>@hs-karlsruhe.de
</a>
```
although I'm not sure if having the adress as text displayed kind of contradicts the idea again since some spam-crawlers are not as dumb as one would think...a better idea might be to display the mailadress as a picture which contains a clickable link and using an alt-tag describing what happens when clicking on the link (regarding accessibility etc.)

Acceptance criteria:

- [ ] no plaintext mail-adresses on the website anymore
- [ ] generate the mailto:-links dynamically on the serverside using e.g. javascript or php after clicking
  - [ ] use some kind of encryption to introduce another level of security

**Comment by Wekra** [comment]
The [overview](https://www.ionos.de/digitalguide/e-mail/e-mail-sicherheit/e-mail-adresse-schuetzen-so-wirds-gemacht/) of 1&1 IONOS could be a good starting point.

**Comment by SimonKienzler** [comment]
From the source you provided, it seems that simple masking has little to no effect, as spam crawlers can still identify them as addresses. If we want to protect them properly, we'd have to go with a more sophisticated approach like encryption or the server-side technique, imo.

**Comment by Wekra** [comment]
Yes, you are right - to be fair, I did the initial research on that **after** I created the issue 😅

**Comment by Wekra** [comment]
I updated the initial issue description with the result of todays tweekly - further input is welcome 😊

**Comment by Wekra** [comment]
Since some people use JavaScript-Blocker, would it be better to go for PHP in order to create the links?
