### ISSUE TITLE
FAQ page displaying not correctly when blocking JavaScript

### ISSUE THREAD

**Issue by Wekra** [fsi-hska/iwi-website#28]
If the browser blocks JavaScript, browsing to the https://iwi-hka.de/faq/ page only displays the file content of the folder instead of rendering the appropriate html page.

Thanks to @Lycentzia for reporting this!

**Comment by milbegreif** [comment]
Same at https://iwi-hka.de/news/

**Comment by SimonKienzler** [comment]
Could be solved by enabling the "Adding a trailing slash" option of Next.js: https://nextjs.org/docs/api-reference/next.config.js/exportPathMap#adding-a-trailing-slash

Would require to change all links on the page to have a trailing slash or alternatively change our .htaccess - which we probably should add to git @milbegreif

**Comment by milbegreif** [comment]
for me it makes no difference which solution we take. 

>>which we probably should add to git @milbegreif
Yes of course we should definitely add it.
