### ISSUE TITLE
Requests to PHP script return 404

### ISSUE THREAD

**Issue by SimonKienzler** [fsi-hska/iwi-website#39]
When accessing e. g. https://iwi-hka.de/scripts/email.php?address=sponsoring I get a 404 instead of a redirect to the appropriate e-mail address. Somethig seems to be misconfigured on the server or the file is really not present. Could you please investigate @milbegreif ?

**Comment by milbegreif** [comment]
I found the issue, the htaccess file blocks the php scripts.

**Comment by SimonKienzler** [comment]
The `.htaccess` file is not yet in version control. Could you send me the file as-is from the server so I can add it to the public directory? It should then be deployed together with all other static files.

**Comment by milbegreif** [comment]
.htaccess modified
