### ISSUE TITLE
Bump PHP-Version

### ISSUE THREAD

**Issue by Wekra** [fsi-hska/iwi-website#43]
Since PHP 7.2 has reached EOL (-> [click](https://www.ionos.de/digitalguide/websites/web-entwicklung/php-72/) ), we should probably upgrade to PHP 8.

**Comment by milbegreif** [comment]
We are working with a higher version than 7.2. I would not post-install a PHP version that is not from the original repos unless absolutely necessary. 

Of course, if our version is EOL, it is necessary. But this will not happen so soon.
