### ISSUE TITLE
Link in calender not click-able

### ISSUE THREAD

**Issue by mapelpapel** [fsi-hska/iwi-website#60]
The link in the calenderbox is not click-able, neither in the description nor in the location field.

**Comment by daniel-vera-g** [comment]
Reminds me about  my PR a while ago: https://github.com/fsi-hska/iwi-website/pull/27

Maybe someone with the Calendar API set up can test it with the `<Link/>` fix ;-)

**Comment by SimonKienzler** [comment]
I will have a look at this, we need to be careful though as we could get problems with XSS if this is not implemented carefully.

Whatever solution we come up with, it should also fix the problem of overflowing long links (as mentioned in #59 )
